server:
  port: 8098

spring:
  application:
    name: youhaowu-member
  datasource:
    url: jdbc:postgresql://192.168.8.112:5432/youhaowu_ums
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.8.112:8848
        namespace: public
        group: DEFAULT_GROUP
        register-enabled: true
  kafka:
    bootstrap-servers: 192.168.8.112:9092

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

logging:
  file:
    path: /tmp
  level:
    com.youhaowu.member: debug
