server:
  port: 8888

spring:
  application:
    name: youhaowu-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.8.112:8848
        namespace: public
        group: DEFAULT_GROUP
        username: nacos
        password: nacos


logging:
  level:
    com.youhaowu.gateway: debug
